#!/bin/bash
 target=$1
 red="\e[31m"
 blink="\e[5m"
 green="\e[32m"
 yellow="\e[33m"
 right=$(printf '\xE2\x9C\x94')
 end="\e[0m"

api=$(cat .token)
shodan init $api > /dev/null
folder=$target-$(date '-I')
rm -rf output/$folder > /dev/null
mkdir -p output/$folder;cd output/$folder
mkdir IP_VULNS

o=$(shodan download $target.json.gz ssl:"$target" 2> /dev/null|grep "Saved");printf ">> ${green}$o${end}\n"
echo "--------------------------------"
shodan parse --fields ip_str,asn,hostnames,port,product,org --separator ":" $target.json.gz > main.data
cat main.data | cut -d":" -f1 | sort -u | httpx -threads 500 -silent | interlace -threads 100 -c "echo _target_; curl --insecure -v _target_ 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'" --silent | egrep "https:\/\/|CN\=|issuer: " | grep -v "^[[:blank:]]*$" | grep -B 1 "\.$1$" | grep -Eo '(http|https)://[^/"]+' | tee alive_ips.txt
cd IP_VULNS;cat ../main.data|awk -F":" '{print $1}'|while read -r line;do shodan host -S $line &> /dev/null;sleep 5;echo -n ">>Hang On<<";done
echo -e "\n"
ls -1 | while read -r line; do
printf "[$right] IP:$end $green $(zcat $line | jq -r ".ip_str" | sort -u | sed -n '1h;2,$H;${g;s/\n/, /g;s/<----- key \(start\|stop\) ----->//g;p}')$end\n"
printf "[$right] ASN:$end $green $(zcat $line | jq -r ".asn" | sort -u | sed -n '1h;2,$H;${g;s/\n/, /g;s/<----- key \(start\|stop\) ----->//g;p}')$end\n"
printf "[$right] Ports:$end $green $(zcat $line | jq -r ".port" | sort -u | sed -n '1h;2,$H;${g;s/\n/, /g;s/<----- key \(start\|stop\) ----->//g;p}')$end\n"
printf "[$right] CVEs:$end $green $(zcat $line | jq -r ".vulns | to_entries[] | .key" 2> /dev/null | sort -u | sed -n '1h;2,$H;${g;s/\n/, /g;s/<----- key \(start\|stop\) ----->//g;p}')$end\n"
echo "----------------------"
done
